<<<<<<< HEAD
#pip show edsl
#pip install git+https://github.com/expectedparrot/edsl.git@main
#grep -n "refresh_rate.*=" /opt/anaconda3/envs/synthetic-twin-agents-env-legacy/lib/python3.12/site-packages/edsl/jobs/jobs_runner_status.py
=======
>>>>>>> origin/main
name: synthetic-twin-agents-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - pingouin
  - statsmodels
  - scikit-learn
  - pip
  - ipykernel
<<<<<<< HEAD
  - git
  - pip:
      - ace_tools
      - git+https://github.com/expectedparrot/edsl.git@main
=======
  - pip:
      - ace_tools
      - edsl==0.1.62
>>>>>>> origin/main
