name: synthetic-twin-agents-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - pingouin
  - statsmodels
  - scikit-learn
  - pip
  - ipykernel
  - pip:
      - ace_tools
      - edsl==0.1.62
